package util;

/**
 * Created by MYK on 2015/12/7 0007.
 */
public enum ListType {
    ADDRESSEEINFOMATION,DISTRIBUTEINFO,GATHERING,LOADINGINFO,ORDER,PAYMENT,RECEIPT,
    RECEIVEINFO,STOCKIN,STOCKOUT,TRANSARRIVE,TRANSINFO
}
